### ISSUE TITLE
Problem while setting up the project

### ISSUE THREAD

**Issue by jai-dewani** [utkarsh-raj/umusic#10]
Even after setting up env file, there seems to be some error with browsing the response object probably due to changes in API response structure

PS: I am using Youtube Data API v3

```
TypeError: E:\Github\umusic\views\index.ejs:6
    4|         <% var i = 0;%>

    5|         <% for (i = 0; i < 4; i++) { %>

 >> 6|             <% if (data.items[i].id.kind === "youtube#video") { %>

    7|                 <div class="row dataField">

    8|                     <div class="col-md-5 img-thumbnail img-responsive">

    9|                         <img src="<%= data.items[i].snippet.thumbnails.medium.url %>">


Cannot read property '0' of undefined
    at eval (eval at compile (E:\Github\umusic\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:26:22)
    at returnedFn (E:\Github\umusic\node_modules\ejs\lib\ejs.js:653:17)
    at tryHandleCache (E:\Github\umusic\node_modules\ejs\lib\ejs.js:251:36)
    at View.exports.renderFile [as engine] (E:\Github\umusic\node_modules\ejs\lib\ejs.js:482:10)
    at View.render (E:\Github\umusic\node_modules\express\lib\view.js:135:8)
    at tryRender (E:\Github\umusic\node_modules\express\lib\application.js:640:10)
    at Function.render (E:\Github\umusic\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (E:\Github\umusic\node_modules\express\lib\response.js:1008:7)
    at Request._callback (E:\Github\umusic\app.js:49:13)
    at Request.self.callback (E:\Github\umusic\node_modules\request\request.js:185:22)
```

**Comment by jai-dewani** [comment]
The API response is the same
There was an error while setting up the .env file

**Comment by utkarsh-raj** [comment]
For anyone having the same error, .env must be set up with the YouTube Data API Key.
Thanks to @jai-dewani for bringing it to notice!
